# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 800)
        self.welcome_lbl = QtWidgets.QLabel(Dialog)
        self.welcome_lbl.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.welcome_lbl.setObjectName("welcome_lbl")
        self.logout_but = QtWidgets.QPushButton(Dialog)
        self.logout_but.setGeometry(QtCore.QRect(160, 10, 127, 39))
        self.logout_but.setObjectName("logout_but")
        self.tbl = QtWidgets.QTableWidget(Dialog)
        self.tbl.setGeometry(QtCore.QRect(10, 70, 680, 721))
        self.tbl.setObjectName("tbl")
        self.tbl.setColumnCount(3)
        self.tbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl.setHorizontalHeaderItem(2, item)
        self.add_but = QtWidgets.QPushButton(Dialog)
        self.add_but.setGeometry(QtCore.QRect(710, 80, 127, 39))
        self.add_but.setObjectName("add_but")
        self.del_but = QtWidgets.QPushButton(Dialog)
        self.del_but.setGeometry(QtCore.QRect(710, 130, 127, 39))
        self.del_but.setObjectName("del_but")
        self.edit_but = QtWidgets.QPushButton(Dialog)
        self.edit_but.setGeometry(QtCore.QRect(710, 180, 127, 39))
        self.edit_but.setObjectName("edit_but")
        self.lst_view = QtWidgets.QListView(Dialog)
        self.lst_view.setGeometry(QtCore.QRect(700, 350, 291, 441))
        self.lst_view.setObjectName("lst_view")
        self.sell_but = QtWidgets.QPushButton(Dialog)
        self.sell_but.setGeometry(QtCore.QRect(710, 230, 127, 39))
        self.sell_but.setObjectName("sell_but")
        self.finish_but = QtWidgets.QPushButton(Dialog)
        self.finish_but.setGeometry(QtCore.QRect(710, 280, 127, 39))
        self.finish_but.setObjectName("finish_but")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcome_lbl.setText(_translate("Dialog", "Welcome User!"))
        self.logout_but.setText(_translate("Dialog", "Logout"))
        item = self.tbl.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tbl.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "product_name"))
        item = self.tbl.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "product_price"))
        self.add_but.setText(_translate("Dialog", "Add"))
        self.del_but.setText(_translate("Dialog", "Delete"))
        self.edit_but.setText(_translate("Dialog", "Edit"))
        self.sell_but.setText(_translate("Dialog", "Sell"))
        self.finish_but.setText(_translate("Dialog", "Finish"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
